version: '3.8'

services:
  web:
    # Production-specific settings
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    restart: always
    # More workers for production
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 --threads 2 run:app
    # Remove development volumes
    volumes:
      - db_data:/app/instance

  # Add Nginx for production
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/static:/usr/share/nginx/html/static:ro
    depends_on:
      - web